In [64]:
#11.27
#numpy练习
import numpy as np
data=np.random.randn(2,3)
data

array([[-1.52879992,  0.98289271,  0.9734554 ],
       [-0.32729891, -1.95545331, -0.80265915]])

In [3]:
data*10

array([[  9.32860862, -15.31498035,  -5.7404166 ],
       [  1.52128541,  15.94379422,  -2.79277044]])

In [4]:
data+data

array([[ 1.86572172, -3.06299607, -1.14808332],
       [ 0.30425708,  3.18875884, -0.55855409]])

In [6]:
#ndarray 是一个多维同类数据容器【多维数组对象】
#ndarry属性：shape数组每一维度的数量；dtype数组的数据类型

data.shape
data.dtype

dtype('float64')

In [7]:
#11.28
#1.生成ndarry
#使用array函数生成数组

data1=[2,3.5,4,8,10]
arr1=np.array(data1)

In [15]:
arr1

array([ 2. ,  3.5,  4. ,  8. , 10. ])

In [9]:
data2=[[1,2,3,],[4,5,6]]
arr2=np.array(data2)

arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2.shape  #说明同等长度的列表，会自动转化为多维数组

(2, 3)

In [16]:
arr2.ndim  # ndim 属性可以查到数组的维度

2

In [17]:
arr1.ndim

1

In [22]:
#除了array之外其他创建数组的函数
#zeros,ones,empty  全0，全1，没有初始化值

np.zeros(5)
np.ones(3)

#这里我发现一个问题，因为np的核心ndarry它只是一个,一个，数据对象，如果这样重复创建，只能生成最后一个

array([0., 0., 0., 0., 0.])

In [26]:
#所以练习的时候只能一个一个的创建才会显示出来，不然会被后面创建的数组对象覆盖
#还有，高维度的时候，不能直接在括号里写维度，而是要在括号里面传入一个元组，即（2，3）
#np.zeros(5,3)不行

np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.dtype

numpy.dtype

In [31]:
test1=np.ones((2,3))

In [32]:
test1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
test1.dtype

dtype('float64')

In [39]:
np.empty((4,2,3)) #四维，两个，三个元素

array([[[2.49970340e+262, 1.46922886e+195, 2.19526581e-152],
        [2.41079391e+198, 9.75023784e+199, 9.04037549e+223]],

       [[2.64521818e+185, 1.41499954e+190, 7.29497550e+175],
        [1.47039297e+224, 5.21974144e+180, 7.49096150e+247]],

       [[2.15074861e-259, 7.04142211e-009, 7.87596779e+276],
        [2.99946775e-067, 6.01334503e-154, 6.01334519e-154]],

       [[5.28595595e-085, 7.47010262e-114, 2.68731797e-110],
        [1.30438623e-076, 7.04142211e-009, 5.98147403e-154]]])

In [ ]:
#以上这些，是返回的未初始化的垃圾值

In [45]:
np.ones_like(5)

array(1)

In [46]:
#2.ndarry 数据类型
#dtype是一种特殊的对象，可以在用np.array()创建数组时写在array括号里面，声明内存信息的数据类型

arr1=np.array([1,2,3],dtype=np.float64)

In [48]:
arr1
arr1.dtype
#我很奇怪为什么这里都不能一次执行多个，显示多个结果？我让她输出arr1和输出数据类型两个不影响啊，都是同一个对象呀，奇怪

dtype('float64')

In [49]:
print(arr1)
print(arr1.dtype)
#使用print就可以了，难道说，这种直接对象，只能输出一个？好吧

[1. 2. 3.]
float64


In [54]:
arr2=np.array([2,3,4.8,6],dtype=np.int32)
arr2.dtype

dtype('int32')

In [55]:
arr2  #因为制定了类型，内部数据就强制转化为整数，直接去掉小数，向下取整

array([2, 3, 4, 6])

In [59]:
#astype 强制转换数据类型
arr2_new=arr2.astype(np.float64)
arr2_new
print(arr2.dtype)

int32


In [60]:
#再来一个练习的例子
arr=np.array([1.3,2.5,4.7])
arr

array([1.3, 2.5, 4.7])

In [71]:
arr.astype(np.int32).dtype

dtype('int32')

In [78]:
#astype还可以将字符串转化为数字
arr_string=np.array(['1.25','2','99.87'])
arr_string

array(['1.25', '2', '99.87'], dtype='<U5')

In [79]:
print(arr_string)

['1.25' '2' '99.87']


In [82]:
arr_string.astype(np.float64).dtype

dtype('float64')

In [83]:
arr_string.astype(np.float64)

array([ 1.25,  2.  , 99.87])

In [84]:
#astype使用后总是能生成一个新的数组！生成一个新的，即使与之前传入的dtype一样
#dtype这个方法还有一个属性，可以在某个数组后面.dtype，即调用和这个数组一样的类型

arr1=np.array([1.2,3.3,5.6],dtype=np.float64)
arr2=np.arange(10)


In [86]:
arr1

array([1.2, 3.3, 5.6])

In [87]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
#现在如果我不知道arr1是什么类型但是我想直接把arr2的类型和arr1的类型一样，可以直接：

arr2.astype(arr1.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#11.29
#numpy数组算数
#数组允许我们进行批量操作，不需要使用for循环，这个是优于列表或者其他类型的，这个特性称之为“向量化”

In [8]:
#例如，两个列表相乘

#list1=[1,2,3,4,5]
#print(list1*list1) #无法做到

#两列表元素内元素相乘只能用for循环
list1=[1,2,3,4,5]
list2=[]
for i in list1:
    list2.append(i*i)
list2

#list1*list1 直接相乘做不到

[1, 4, 9, 16, 25]

In [5]:
#数组的算数操作
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [10]:
arr-2*arr+arr

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
#因为数组会把计算参数传给数组中的每一个元素

1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [12]:
arr*5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [17]:
arr2=np.array([[2,4,6],[1,2,9]])
arr2

array([[2, 4, 6],
       [1, 2, 9]])

In [15]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr>arr2 
#同尺寸数组之间比较，会一个一个元素对应位置的比较，产生一个新的元素是布尔值的数组！！！
#注意哦，会生成一个对应的布尔值数组哦！生成新数组哦！

array([[False, False, False],
       [ True,  True, False]])

In [19]:
#数组也可以切片和索引
arr=np.arange(10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[2] #索引

2

In [23]:
arr[3:8] #依然遵循左闭右开原则

array([3, 4, 5, 6, 7])

In [26]:
arr[3:8]=12 #还可以用这种方法改变数组内的元素
arr
#值被传递给了数组切片，数组切片相当于数组的视图！视图！
#所以和列表不同的是，切片并不是复制数据，而只是一个视图窗口而已！

array([ 0,  1,  2, 12, 12, 12, 12, 12,  8,  9])

In [27]:
#对于视图的修改也会反映到原数组上
arr_slice=arr[3:8]
arr_slice

array([12, 12, 12, 12, 12])

In [28]:
arr_slice[4]=100
arr_slice

array([ 12,  12,  12,  12, 100])

In [29]:
arr #通过修改了它视图的内容，其原本数组也相应修改了

array([  0,   1,   2,  12,  12,  12,  12, 100,   8,   9])

In [30]:
arr_slice[:]=0 #引用所有元素

In [31]:
arr_slice

array([0, 0, 0, 0, 0])

In [32]:
#如果不想要切片视图，想让视图变成一个新数组，可以拷贝
arr_new=arr_slice.copy()
arr_new

array([0, 0, 0, 0, 0])

In [33]:
arr_new[:]=5  #复制成功，改变新数组，而不是视图，不影响原有数组
arr

array([0, 1, 2, 0, 0, 0, 0, 0, 8, 9])

In [34]:
arr_new

array([5, 5, 5, 5, 5])

In [36]:
#高维度数组，切片出来的是一个数组，而不是一个值
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9],[0,0,0]])
arr2d[2:4]

array([[7, 8, 9],
       [0, 0, 0]])

In [42]:
#如果要切出值，是不是可以用二维切片？我试试 
arr2d[2][1]   
#还真的可以，但是出来的就是元素本身了

8

In [45]:
arr2d[2,1]
#效果相同

8

In [43]:
#但是如果第二个是两个元素，则出来还是数组
arr2d[2][1:3]
#而且我发现，这个元素是可以超索引的，3其实长度已经超索引了，但是没有报错

array([8, 9])

In [ ]:
#自己强化练习——写在review昨天的那里了#11.29

In [46]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [47]:
arr2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
arr2d[:1,:2] #还可以这样√

array([[1, 2]])

In [56]:
#新知识：布尔索引
#在索引数组时，是可以传入布尔值的，即索引出ture对应的行

arr=np.array(['ann','bob','jun','ann','jun','jun','bob'])
arr

array(['ann', 'bob', 'jun', 'ann', 'jun', 'jun', 'bob'], dtype='<U3')

In [95]:
arr2=np.random.randn(7,4)

In [58]:
arr2

array([[ 1.12889557,  2.27683887, -2.03829014,  0.41932037],
       [-0.40019931,  0.25822831, -0.47125045,  2.49619148],
       [ 0.46514624, -0.53963768,  2.28260393,  0.20702758],
       [-0.17269057,  1.12208012, -0.60073193,  1.22990977],
       [-1.07541847,  1.61577271,  0.63267282,  1.1284891 ],
       [-0.16496586, -1.63516986,  0.40834121, -2.63807724],
       [ 2.19736639,  0.54776719, -0.48978844, -0.46483168]])

In [59]:
arr=='ann' #批量比较操作

array([ True, False, False,  True, False, False, False])

In [60]:
arr2[arr=='ann'] 
#重点
#可以这样做的，索引时可以传入布尔值的，布尔值对应ture的行数就出来
#但是布尔值数组的长度必须和需要索引的数组长度一致！

array([[ 1.12889557,  2.27683887, -2.03829014,  0.41932037],
       [-0.17269057,  1.12208012, -0.60073193,  1.22990977]])

In [61]:
arr2[arr=='ann',:2]

array([[ 1.12889557,  2.27683887],
       [-0.17269057,  1.12208012]])

In [67]:
#其他比较符号也可以

arr!='jun'

#问题：
#为什么 arr!='jun'& arr!='ann' 不可以，报错？

array([ True,  True, False,  True, False, False,  True])

In [69]:
arr2[arr!='jun',:1]

array([[ 1.12889557],
       [-0.40019931],
       [-0.17269057],
       [ 2.19736639]])

In [71]:
# arr2[~(arr!='jun',:1)]
#这样不行
#~是取反，但是只能针对某一个通用条件使用，不能对两个分离的表达式使用

In [75]:
#arr2[~(arr!='jun'),~:1]
#这样也不行，只能对条件使用，对切片表达式无法使用

SyntaxError: invalid syntax (<ipython-input-75-6985b5974ee2>, line 1)

In [76]:
arr2[~(arr!='jun'),2:]

array([[ 2.28260393,  0.20702758],
       [ 0.63267282,  1.1284891 ],
       [ 0.40834121, -2.63807724]])

In [81]:
#刚刚那个问题：为什么 arr!='jun'& arr!='ann' 不可以，报错？ 解决了
#因为我没有加括号

In [79]:
(arr!='jun')& (arr!='ann') #加括号才可以，不然&符号前后会引起歧义

#另外，and是 &，or是 \ 

array([False,  True, False, False, False, False,  True])

In [82]:
arr2[(arr!='jun')& (arr!='ann')]

array([[-0.40019931,  0.25822831, -0.47125045,  2.49619148],
       [ 2.19736639,  0.54776719, -0.48978844, -0.46483168]])

In [83]:
arr2

array([[ 1.12889557,  2.27683887, -2.03829014,  0.41932037],
       [-0.40019931,  0.25822831, -0.47125045,  2.49619148],
       [ 0.46514624, -0.53963768,  2.28260393,  0.20702758],
       [-0.17269057,  1.12208012, -0.60073193,  1.22990977],
       [-1.07541847,  1.61577271,  0.63267282,  1.1284891 ],
       [-0.16496586, -1.63516986,  0.40834121, -2.63807724],
       [ 2.19736639,  0.54776719, -0.48978844, -0.46483168]])

In [85]:
#也可以用相当于true的常识来设置索引参数
#比如：

arr2[arr2<0]=0 #这样也是ok的

In [94]:
arr2

array([[1.        , 1.        , 1.        , 1.        ],
       [0.        , 0.25822831, 0.        , 2.49619148],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [2.19736639, 0.54776719, 0.        , 0.        ]])

In [87]:
arr

array(['ann', 'bob', 'jun', 'ann', 'jun', 'jun', 'bob'], dtype='<U3')

In [90]:
#arr2[arr!='bob']=1 #也是可以的

In [96]:
arr2

array([[-1.44209821, -1.29644905, -0.97530627, -0.54796884],
       [-0.90834972,  0.85086426,  1.55920316, -0.36982912],
       [-0.90588586, -1.22727572,  0.68639775,  0.71214166],
       [-1.62292438,  0.85759243, -0.34601889,  1.03922284],
       [-0.80639345, -0.60744296, -0.70280654, -0.95214166],
       [ 0.24221675,  0.69270489,  0.34106065,  0.23154147],
       [-1.42550364,  0.6721091 , -0.22215695, -0.11037156]])

In [92]:
#逻辑分解：
arr!='bob'

array([ True, False,  True,  True,  True,  True, False])

In [97]:
arr2[arr!='bob']

array([[-1.44209821, -1.29644905, -0.97530627, -0.54796884],
       [-0.90588586, -1.22727572,  0.68639775,  0.71214166],
       [-1.62292438,  0.85759243, -0.34601889,  1.03922284],
       [-0.80639345, -0.60744296, -0.70280654, -0.95214166],
       [ 0.24221675,  0.69270489,  0.34106065,  0.23154147]])

In [98]:
arr2[arr!='bob']=1

In [99]:
arr2

array([[ 1.        ,  1.        ,  1.        ,  1.        ],
       [-0.90834972,  0.85086426,  1.55920316, -0.36982912],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ],
       [-1.42550364,  0.6721091 , -0.22215695, -0.11037156]])

In [100]:
#神奇索引：numpy的一个专业术语
#使用整数数组进行数据索引【索引值可传入数组或列表】
arr=np.empty((8,4))

In [101]:
arr

array([[1.69338334e-152, 6.01347002e-154, 6.01347002e-154,
        1.50644566e+161],
       [1.69338334e-152, 5.98150366e-154, 2.43581185e-152,
        2.43581185e-152],
       [7.26615871e+223, 8.88755841e+247, 2.88525112e+214,
        5.74371512e+257],
       [1.77459490e+248, 3.01468689e+161, 1.23559428e-259,
        2.21525718e+214],
       [2.19827701e+214, 4.83245960e+276, 4.37338391e+257,
        3.58252558e+246],
       [4.83245960e+276, 1.00109757e+229, 2.09054211e-115,
        6.62276948e+265],
       [6.01334504e-154, 2.43581185e-152, 2.43581185e-152,
        7.26615871e+223],
       [9.77081644e+199, 4.53079576e-090, 1.01176682e+261,
        1.91084650e+214]])

In [103]:
for i in range(8):
    arr[i]=i*10
arr

array([[ 0.,  0.,  0.,  0.],
       [10., 10., 10., 10.],
       [20., 20., 20., 20.],
       [30., 30., 30., 30.],
       [40., 40., 40., 40.],
       [50., 50., 50., 50.],
       [60., 60., 60., 60.],
       [70., 70., 70., 70.]])

In [104]:
#1，传入列表/数组，得出按列表中数字顺序出现的子集

arr[[1,3,5]]
#传入列表，即得到轩中1，3，5行的子数组

array([[10., 10., 10., 10.],
       [30., 30., 30., 30.],
       [50., 50., 50., 50.]])

In [105]:
arr2=np.array([1,2])

In [106]:
arr2

array([1, 2])

In [107]:
arr[arr2] #传入数组得到第一第二行

array([[10., 10., 10., 10.],
       [20., 20., 20., 20.]])

In [108]:
#如果是负索引，则从后往前的顺序
arr[arr2[:]*(-1)] #得到最后两行

array([[70., 70., 70., 70.],
       [60., 60., 60., 60.]])

In [109]:
arr[[-1,-3,-5]]#得到从后往前数的三行

array([[70., 70., 70., 70.],
       [50., 50., 50., 50.],
       [30., 30., 30., 30.]])

In [114]:
#啊啊啊，reshape这个方法，超级强大，可以重组数组形状，一维数组和多维数组之间可以相互转化
arr=np.arange(12)

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [116]:
arr.reshape(3,4)
#注意：这个写法不规范，规范的应该是括号里面再括号（（3，4））

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
arr.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [122]:
#创建列表的时候就可以直接用reshape来指定维度
arr=np.arange(6).reshape((2,3))

In [123]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [125]:
#神奇索引不想切片那样是视图，而是复制到一个新的数组里面

arr=np.arange(32).reshape((8,4))

In [126]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [127]:
arr[2,3]

11

In [129]:
arr[[1,7],3]

array([ 7, 31])

In [140]:
arr[[1,7]][3]
#为什么这样就不行呢,哦，我知道了，它是按顺序的，第一个[1,7]索引完了之后,得出来的是2行，4列，如果索引值超过2，就超过了

IndexError: index 3 is out of bounds for axis 0 with size 2

In [136]:
arr[2][3] #这样又可以

11

In [137]:
arr[[1,7]]
#得出来的是2行，4列，如果索引值超过2，就超过了长度，报错

array([[ 4,  5,  6,  7],
       [28, 29, 30, 31]])

In [145]:
#但是为什么合在一起的又可以呢？
arr[[1,7],3]

array([ 7, 31])

In [148]:
arr[[1,5,7,2]][:]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [152]:
arr[[1,5,7,2]][:,[0,3,1,2]]
#这个真的很神奇了。[0,3,1,2]是索引的列的顺序从左到右排列！666

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [153]:
#T属性，数组行列转置：数组.T

arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [156]:
# dot（）方法计算数组矩阵的内积:np.dot()

arr1=np.array([1,2,3,4]).reshape((2,2))
arr2=np.array([5,6,7,8]).reshape((2,2))

In [160]:
#计算两个矩阵相乘（注意，和数组相乘不同，数组相乘只是对应位置上的数字相乘arr1*arr2）,这个内积是求矩阵的乘积

np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [ ]:
#ok

In [165]:
#还有一个更高级的，transpose()方法，高维数组的置换轴，即XY轴交换，或者xyz轴交换，甚至xyzh...等更高维度
#有一个规则（x，y）是（0，1），（x，y，z）是（0，1，2）

arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [166]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
#ok

In [167]:
#还有一个swapaxes方法，接收一对轴编号作为参数，对轴进行调整用于数据重组
#返回的是视图
#这个大概理解就是：arr是一个（x,y,z）的三维数组即（0，1，2）
#现在我要取（1，2），就是y,z的组合，那就是第二第三层，大概能理解
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [168]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [ ]:
#学习总结：今天的内容很多，吧ndarry部分都学完了，就是一个多维数组对象的很多方法和操作，很棒！