In [1]:
#numpy练习
import numpy as np
data=np.random.randn(2,3)
data

array([[ 0.85286198,  0.51744706,  0.45265482],
       [-0.08206909, -1.6176991 ,  0.45001762]])

In [2]:
data*10

array([[  8.52861985,   5.17447061,   4.5265482 ],
       [ -0.82069089, -16.17699095,   4.50017619]])

In [3]:
data+data

array([[ 1.70572397,  1.03489412,  0.90530964],
       [-0.16413818, -3.23539819,  0.90003524]])