In [64]:
#numpy练习
import numpy as np
data=np.random.randn(2,3)
data

array([[-1.52879992,  0.98289271,  0.9734554 ],
       [-0.32729891, -1.95545331, -0.80265915]])

In [3]:
data*10

array([[  9.32860862, -15.31498035,  -5.7404166 ],
       [  1.52128541,  15.94379422,  -2.79277044]])

In [4]:
data+data

array([[ 1.86572172, -3.06299607, -1.14808332],
       [ 0.30425708,  3.18875884, -0.55855409]])

In [6]:
#ndarray 是一个多维同类数据容器【多维数组对象】
#ndarry属性：shape数组每一维度的数量；dtype数组的数据类型

data.shape
data.dtype

dtype('float64')

In [7]:
#1.生成ndarry
#使用array函数生成数组

data1=[2,3.5,4,8,10]
arr1=np.array(data1)

In [15]:
arr1

array([ 2. ,  3.5,  4. ,  8. , 10. ])

In [9]:
data2=[[1,2,3,],[4,5,6]]
arr2=np.array(data2)

arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr2.shape  #说明同等长度的列表，会自动转化为多维数组

(2, 3)

In [16]:
arr2.ndim  # ndim 属性可以查到数组的维度

2

In [17]:
arr1.ndim

1

In [22]:
#除了array之外其他创建数组的函数
#zeros,ones,empty  全0，全1，没有初始化值

np.zeros(5)
np.ones(3)

#这里我发现一个问题，因为np的核心ndarry它只是一个,一个，数据对象，如果这样重复创建，只能生成最后一个

array([0., 0., 0., 0., 0.])

In [26]:
#所以练习的时候只能一个一个的创建才会显示出来，不然会被后面创建的数组对象覆盖
#还有，高维度的时候，不能直接在括号里写维度，而是要在括号里面传入一个元组，即（2，3）
#np.zeros(5,3)不行

np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.dtype

numpy.dtype

In [31]:
test1=np.ones((2,3))

In [32]:
test1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
test1.dtype

dtype('float64')

In [39]:
np.empty((4,2,3)) #四维，两个，三个元素

array([[[2.49970340e+262, 1.46922886e+195, 2.19526581e-152],
        [2.41079391e+198, 9.75023784e+199, 9.04037549e+223]],

       [[2.64521818e+185, 1.41499954e+190, 7.29497550e+175],
        [1.47039297e+224, 5.21974144e+180, 7.49096150e+247]],

       [[2.15074861e-259, 7.04142211e-009, 7.87596779e+276],
        [2.99946775e-067, 6.01334503e-154, 6.01334519e-154]],

       [[5.28595595e-085, 7.47010262e-114, 2.68731797e-110],
        [1.30438623e-076, 7.04142211e-009, 5.98147403e-154]]])

In [ ]:
#以上这些，是返回的未初始化的垃圾值

In [45]:
np.ones_like(5)

array(1)

In [46]:
#2.ndarry 数据类型
#dtype是一种特殊的对象，可以在用np.array()创建数组时写在array括号里面，声明内存信息的数据类型

arr1=np.array([1,2,3],dtype=np.float64)

In [48]:
arr1
arr1.dtype
#我很奇怪为什么这里都不能一次执行多个，显示多个结果？我让她输出arr1和输出数据类型两个不影响啊，都是同一个对象呀，奇怪

dtype('float64')

In [49]:
print(arr1)
print(arr1.dtype)
#使用print就可以了，难道说，这种直接对象，只能输出一个？好吧

[1. 2. 3.]
float64


In [54]:
arr2=np.array([2,3,4.8,6],dtype=np.int32)
arr2.dtype

dtype('int32')

In [55]:
arr2  #因为制定了类型，内部数据就强制转化为整数，直接去掉小数，向下取整

array([2, 3, 4, 6])

In [59]:
#astype 强制转换数据类型
arr2_new=arr2.astype(np.float64)
arr2_new
print(arr2.dtype)

int32


In [60]:
#再来一个练习的例子
arr=np.array([1.3,2.5,4.7])
arr

array([1.3, 2.5, 4.7])

In [71]:
arr.astype(np.int32).dtype

dtype('int32')

In [78]:
#astype还可以将字符串转化为数字
arr_string=np.array(['1.25','2','99.87'])
arr_string

array(['1.25', '2', '99.87'], dtype='<U5')

In [79]:
print(arr_string)

['1.25' '2' '99.87']


In [82]:
arr_string.astype(np.float64).dtype

dtype('float64')

In [83]:
arr_string.astype(np.float64)

array([ 1.25,  2.  , 99.87])

In [84]:
#astype使用后总是能生成一个新的数组！生成一个新的，即使与之前传入的dtype一样
#dtype这个方法还有一个属性，可以在某个数组后面.dtype，即调用和这个数组一样的类型

arr1=np.array([1.2,3.3,5.6],dtype=np.float64)
arr2=np.arange(10)


In [86]:
arr1

array([1.2, 3.3, 5.6])

In [87]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
#现在如果我不知道arr1是什么类型但是我想直接把arr2的类型和arr1的类型一样，可以直接：

arr2.astype(arr1.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])